- hosts: webservers
  vars:
    user_name: Chandan
    http_port: 8080
  tasks:
    - yum: pkg=httpd state=installed
    - template: 
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
    - service: name=httpd state=running

    - template:
        src: example-template.j2
        dest: /tmp/jinta-output
    - debug: var=play_hosts

- hosts: webservers
  vars:
    user_name: Chandan
  tasks:
    - template:
        src: example-template-2.j2
        dest: /tmp/jinta-loop-output
